language: ruby

env:
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.1.1"
  - "RAILS_VERSION=4.2.4"
  - "RAILS_VERSION=master"

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2

matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"

before_install:
  - gem update bundler

before_script:
  - bundle exec rake app:db:migrate

script: bundle exec rake spec
