language: ruby

env:
  - "RAILS_VERSION=4.2"
  - "RAILS_VERSION=5.1"
  - "RAILS_VERSION=master"

rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0

matrix:
  fast_finish: true
  allow_failures:
    - env: "RAILS_VERSION=master"
  include:
    - rvm: 2.2
      env: RAILS_VERSION=4.2

before_install:
  - gem update bundler

before_script:
  - bundle exec rake app:db:migrate

script: bundle exec rake spec
